### ISSUE TITLE
Incorrect wsdl address in Sprinboot example

### ISSUE THREAD

**Issue by milka12** [CA-DevTest/CodeSV#3]
In the[ Springboot example documentation](https://github.com/CA-DevTest/CodeSV/tree/master/codesv-examples/springboot-virtualized-soap-example) the correct WSDL address is "http://localhost:9090/codesv/ws/helloworld.wsdl" not "http://localhost:9090/codenotfound/ws/helloworld.wsdl"

**Comment by rjakubco** [comment]
Thank you @milka12 for pointing out this mistake! It is really appreciated.

Fixed in master.
