### ISSUE TITLE
Second test with long response hangs with jetty 9.4

### ISSUE THREAD

**Issue by mykhaliev** [CA-DevTest/CodeSV#6]
I am trying to virtualize http service. I have two similar tests in one class, second test hangs if I run whole class. Also if I would create 2 files that have such test in one package, and run all tests in package, it would hang on second file test.
If I run tests independently both are successful.
Also I found that this happens only when I use Jetty server 9.4, but it works on 9.2 version.

Example of test:
``` java
byte[] b = new byte[10000];
new Random().nextBytes(b);
String responseBodyToSend = new String(b);
forPost("http://test.com:8080/deploy/").doReturn(serverErrorMessage().withStringBody(responseBodyToSend));

HttpPost httpPost = new HttpPost("http://test.com:8080/deploy/");
HttpClient client = HttpClientBuilder.create().build();
HttpResponse response = client.execute(httpPost);
String responseBody = EntityUtils.toString(response.getEntity());
Assert.assertEquals(responseBody, responseBodyToSend);

```

**Comment by rjakubco** [comment]
Fixed in CodeSV 1.3.0 release.
