### ISSUE TITLE
Source Code for CodeSV

### ISSUE THREAD

**Issue by Purus** [CA-DevTest/CodeSV#7]
Where can I find the source code? Is this a closed-source free library?

**Comment by hrabosch** [comment]
Hi Purus,
Yes, CodeSV is closed-source free library and we are storing only code examples here on GitHub.
But feel free to contact me, if you'd like to know more about CodeSV.
Regards,
Ales

**Comment by hrabosch** [comment]
@Purus I am closing this issue due to no response from you. Feel free to open a new issue in case of future questions or suggestions.
Thank you,
Ales
